<?php

namespace Gouzzy\GamesCollectionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EditorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditorRepository extends EntityRepository
{
}
