<?php

namespace Gouzzy\GamesCollectionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function findAllOrderByConsole()
    {
        return $this->createQueryBuilder('g')
                    ->leftJoin('g.console','c')
                    ->leftJoin('c.brand','b')
                    ->orderBy('b.name,c.name,g.name', 'asc')
                    ->getQuery() 
                    ->getResult();
    }
}
