<?php

namespace Gouzzy\GamesCollectionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GamePictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamePictureRepository extends EntityRepository
{
}
